#!/usr/bin/env python

import sys
from lib import actions

print "Restarting RealTime server"
try:
    actions.restart(quiet=True)    
except Exception, e:
    print str(e)
    sys.exit(255)

sys.exit(0)
