#!/bin/bash

DIR="$( cd -P "$( dirname "$0" )" && pwd )"

CLEAN=""
if [[ $1 == "clean" ]]; then
    CLEAN="-c"
fi

if [[ $GOOS == "linux" ]]
then
    cd ${DIR}/realtime && gb $CLEAN -b -v 
else
    cd $DIR && gb $CLEAN -b -v 
fi
